### ISSUE TITLE
Shotgun breaking in Ruby 1.9.2

### ISSUE THREAD

**Issue by gobr** [rtomayko/shotgun#26]
Hi,

I've been facing an issue with shotgun 0.8 over Ruby 1.9.2. Running a simple Sinatra application using `shotgun index.rb` I got an error "Boot Error" - complete traceback copied below.
I believe it's due to the fact Ruby 1.9.2 seems not to include current working directory in its import path. Adding the following statement before line 114 in lib/shotgun/loader - where shotgun tries to import index.rb - everything seems to work fine again.

```
$:.unshift("#{`pwd`}".chomp)
```

Complete traceback:

```
Boot Error

Something went wrong while loading index.rb

LoadError: no such file to load -- index.rb

<internal:lib/rubygems/custom_require>:29:in `require'
<internal:lib/rubygems/custom_require>:29:in `require'
/Users/gobr/.rvm/gems/ruby-1.9.2-p0/gems/shotgun-0.8/lib/shotgun/loader.rb:114:in `inner_app'
/Users/gobr/.rvm/gems/ruby-1.9.2-p0/gems/shotgun-0.8/lib/shotgun/loader.rb:102:in `assemble_app'
/Users/gobr/.rvm/gems/ruby-1.9.2-p0/gems/shotgun-0.8/lib/shotgun/loader.rb:86:in `proceed_as_child'
/Users/gobr/.rvm/gems/ruby-1.9.2-p0/gems/shotgun-0.8/lib/shotgun/loader.rb:31:in `call!'
/Users/gobr/.rvm/gems/ruby-1.9.2-p0/gems/shotgun-0.8/lib/shotgun/loader.rb:18:in `call'
/Users/gobr/.rvm/gems/ruby-1.9.2-p0/gems/shotgun-0.8/lib/shotgun/favicon.rb:12:in `call'
/Users/gobr/.rvm/gems/ruby-1.9.2-p0/gems/rack-1.2.1/lib/rack/builder.rb:77:in `call'
/Users/gobr/.rvm/gems/ruby-1.9.2-p0/gems/rack-1.2.1/lib/rack/content_length.rb:13:in `call'
/Users/gobr/.rvm/gems/ruby-1.9.2-p0/gems/rack-1.2.1/lib/rack/handler/webrick.rb:52:in `service'
/Users/gobr/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/webrick/httpserver.rb:111:in `service'
/Users/gobr/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/webrick/httpserver.rb:70:in `run'
/Users/gobr/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/webrick/server.rb:183:in `block in start_thread'
```

Thanks due to github.com/rafaelcv for sharing his discoveries on this.

Salute,
Diego 'gobr' Henrique.

**Comment by adsr13** [comment]
When I run 'shotgun' from the terminal I get this: 'Configuration config.ru file not found 
I'm pretty new to all of this and could use some baby help. I'm trying to run my very first Sinatra project and got bored of restarting the server, and trying out Shotgun to no avail. Thanks for your help in advance!
