### ISSUE TITLE
Unexpected error while processing request: end of file reached

### ISSUE THREAD

**Issue by fbjork** [rtomayko/shotgun#27]
Getting the error using the latest shotgun, thin 1.2.7, rails 3.0.1 and ruby 1.9.2:
!! Unexpected error while processing request: end of file reached

any ideas?

**Comment by bbiglari** [comment]
I have the same error in Siantra app, and I cannot see a solution here, why this has been closed then?

**Comment by djanowski** [comment]
@bbiglari Can you provide a self-contained example to reproduce?
