### ISSUE TITLE
Shotgun Doesn't Respond to SIGTERM

### ISSUE THREAD

**Issue by Wardrop** [rtomayko/shotgun#33]
Shotgun does not seem to respond to the SIGTERM process signal, which can make starting and stopping shotgun and real pain, as the common CTRL+C doesn't kill it. Is there any reason for this? If not, is it something that can be fixed in a future version?

Cheers

**Comment by djanowski** [comment]
It's working for me, even on 1.8.7. So please reopen if still an issue.
