### ISSUE TITLE
Using rack 1.3.2 and sinatra no logging is visible

### ISSUE THREAD

**Issue by capitaomorte** [rtomayko/shotgun#34]
`ruby app.rb` shows me standard Apache log messages, but `shotgun app.rb` doesn't. The app works fine and reloading works. This happens with Rack 1.3.2 and latest mongrel/webrick. Using [ruby-1.8.7-p352]. Tell me if you can't reproduce and/or need more info.

app.rb as in sinatrarb.com's homepage

**Comment by djanowski** [comment]
Closing in favor of #57.

**Comment by djanowski** [comment]
The fix is released in 0.9.1.
