### ISSUE TITLE
No output from Rack::CommonLogger

### ISSUE THREAD

**Issue by cyx** [rtomayko/shotgun#39]
The simplest way I could make it work was by doing this:

https://github.com/cyx/shotgun/commit/30985301f367dbec2eaae8a808ee944ed7faf32c

I know it's a bit hackish though. I tried also experimenting with reopening $stderr / $stdout after forking to the previous values, but unfortunately I couldn't find a way to make it work properly.

Thanks in advance for any help!

**Comment by djanowski** [comment]
Closing in favor of #57. I intend to merge this very soon. Thanks.

**Comment by djanowski** [comment]
The fix is released in 0.9.1.
