### ISSUE TITLE
Sinatra `enable :lock` doesn't work with Shotgun

### ISSUE THREAD

**Issue by bachue** [rtomayko/shotgun#52]
Hi, 

As I'm using sqlite3 as a dev db, sometimes when I send lots of requests to server at the same time, sqlite3 db file could be locked.
I tried to `enable :lock` then Sinatra can't deal with many requests parallel, but with Shotgun, it seems that this option doesn't work. Can you help?

Thanks.

**Comment by djanowski** [comment]
What do you mean by lots of requests?
