### ISSUE TITLE
LoadError when requiring 'net/ldap' gem

### ISSUE THREAD

**Issue by safetymonkey** [rtomayko/shotgun#54]
When using Shotgun to load my Sinatra app ($ shotgun app.rb) I get the following error as I try to load the webpage (no error appears in the console):

    Boot Error

    Something went wrong while loading config.ru

    LoadError: cannot load such file -- net/ldap

    /home/<user>/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `require'
    /home/<user>/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `block in require'
    /home/<user>/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:214:in `load_dependency'
    /home/<user>/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `require'
    config.ru:4:in `block in inner_app'
    /home/<user>/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.4.2/lib/rack/builder.rb:51:in `instance_eval'
    /home/<user>/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.4.2/lib/rack/builder.rb:51:in `initialize'
    config.ru:1:in `new'
    config.ru:1:in `inner_app'
    /home/<user>/.rvm/gems/ruby-2.0.0-p247/gems/shotgun-0.9/lib/shotgun/loader.rb:112:in `eval'
    /home/<user>/.rvm/gems/ruby-2.0.0-p247/gems/shotgun-0.9/lib/shotgun/loader.rb:112:in `inner_app'
    /home/<user>/.rvm/gems/ruby-2.0.0-p247/gems/shotgun-0.9/lib/shotgun/loader.rb:102:in `assemble_app'
    /home/<user>/.rvm/gems/ruby-2.0.0-p247/gems/shotgun-0.9/lib/shotgun/loader.rb:86:in `proceed_as_child'
    /home/<user>/.rvm/gems/ruby-2.0.0-p247/gems/shotgun-0.9/lib/shotgun/loader.rb:31:in `call!'
    /home/<user>/.rvm/gems/ruby-2.0.0-p247/gems/shotgun-0.9/lib/shotgun/loader.rb:18:in `call'
    /home/<user>/.rvm/gems/ruby-2.0.0-p247/gems/shotgun-0.9/lib/shotgun/favicon.rb:12:in `call'
    /home/<user>/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.4.2/lib/rack/builder.rb:134:in `call'
    /home/<user>/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.4.2/lib/rack/handler/webrick.rb:59:in `service'
    /home/<user>/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
    /home/<user>/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
    /home/<user>/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'

When I load the app via the Ruby command ($ ruby app.rb), everything loads and works properly. This behavior began when I added a line requiring 'net/ldap', which is called out in the error. I've been digging around for about an hour and I can't seem to find any indication why this would happen. Below are the relevant require lines from app.rb:

    require 'rubygems'
    require 'sinatra'
    require 'net/ldap' # gem install net-ldap
    Dir.glob('./{models,helpers,controllers}/*.rb').each { |file| require file }

    configure do
      set :public_folder, Proc.new { File.join(root, "static") }
      enable :sessions
      set :session_secret, '<secret goes  here>'
    end

I have tried both "require 'net-ldap'" and "require 'net/ldap'" and they produce the same results.

**Comment by djanowski** [comment]
@safetymonkey Can you please let us know if this is still an issue? If so, can you provide a standalone repo (a gist?) so that we can reproduce? Thanks!

**Comment by safetymonkey** [comment]
Using the following gem versions I am no longer able to reproduce the issue. Thanks!

shotgun -- 0.9
sinatra -- 1.4.4
net-ldap -- 0.7.0
