### ISSUE TITLE
Incompatible with SuckerPunch Async

### ISSUE THREAD

**Issue by stevendaniels** [rtomayko/shotgun#58]
[sucker_punch](https://github.com/brandonhilkert/sucker_punch) is a gem that runs job from memory; it uses celluloid. 

If I use Shotgun with sucker_punch's async command, then the command silently fails. I don't have this problem with other servers. Here's a [gist that reproduces the issue](https://gist.github.com/stevendaniels/9b62bcd8957e3b193cfe).

I also raised a similar issue on the [sucker_punch repo](https://github.com/brandonhilkert/sucker_punch/issues/117), but after further investigation, I believe the issue is caused by shotgun.

**Comment by djanowski** [comment]
Yes, I don't think Shotgun will be compatible with something that is long-lived like consuming a queue.
