### ISSUE TITLE
The way shotgun run

### ISSUE THREAD

**Issue by mymai91** [rtomayko/shotgun#60]
I'm finding out the way Shotgun run. 
To shotgun run we have to use ```Shotgun::Loader.new(env)``` 
It start at step ```initialize``` I don't see anything to invoke method ```call``` to continue run.
Please help me clearer.
Thanks

**Comment by rtomayko** [comment]
Hi @mymai91, the `call` method is run by the web server each time a web request comes in.

I can help. What are you trying to do?

**Comment by mymai91** [comment]
@rtomayko Hi, I just curious the way Shotgun run. Continuing find out. But your answer makes me clearer.
Thank you.

**Comment by mymai91** [comment]
@rtomayko Will ask more when I encounter issue.

**Comment by mymai91** [comment]
@rtomayko : I have a question. If I don't invoke `call` method. Is there any way to make it run?

**Comment by djanowski** [comment]
Please reopen if this is still an issue. Thanks.
