### ISSUE TITLE
Rack 2.0.1 breaks requiring rack in bin/shotgun

### ISSUE THREAD

**Issue by jekuta** [rtomayko/shotgun#62]
Rack 2.0.1 that was just released yesterday changes the names of the submodules.
https://github.com/rack/rack/commit/857641dab255dbec490fead1d3a0f1ff999b2137

Since there is no pessimistic version constraint in gemspec, this breaks the bin/shotgun that reference to the old naming.
https://github.com/rtomayko/shotgun/blob/master/bin/shotgun#L112

**Comment by djanowski** [comment]
Released as 0.9.2. Thank you and apologies for the delay.
