### ISSUE TITLE
Doesn't work on macOS High Sierra

### ISSUE THREAD

**Issue by rprandi** [rtomayko/shotgun#69]
Hello,

This gem no longer works on macOS High Sierra.

I noticed it is only compatible with systems that support fork(2) and High Sierra does change how fork() works on syscall level.

**Comment by rprandi** [comment]
the problem is:

== Shotgun/WEBrick on http://127.0.0.1:8999/
objc[89654]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called.
objc[89654]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
[2017-10-04 13:36:39] ERROR EOFError: end of file reached

**Comment by rprandi** [comment]
Well i know this will probably never get fixed, but for reference if any of the forks wish to solve it, i found this article explaining the problem:

https://blog.phusion.nl/2017/10/13/why-ruby-app-servers-break-on-macos-high-sierra-and-what-can-be-done-about-it/

The article also mentions a workaround:

```export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES```

**Comment by jwillette-sh** [comment]
this fixed it https://github.com/rtomayko/shotgun/issues/69#issuecomment-338401331

**Comment by osxgirl** [comment]
Well, this is helpful as well in the Beta of Mac OS Mojave. Thank you.

// ♥ objc[3502]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called.
objc[3502]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

**Comment by fmquaglia** [comment]
worked for me after upgrading to Mojave. Thank you <3

**Comment by lucasklaassen** [comment]
For anyone coming here that upgrades to Mojave and exports the env variable and it still doesn't work, please please please run `xcode-select --install` and then make sure to open the Xcode app as it will ask you to install some additional components to get it running. Then restart your mac and it should be gucci.

**Comment by ghost** [comment]
Hi,
Thanks to all of you found this useful :-) and to add to Lucas keep an up to date software

**Comment by vsage** [comment]
For people still having this issue in Mojave, try upgrading ruby to a version >= 2.4.4 in the Gemfile and run `bundle install`

**Comment by dongido001** [comment]
Worked for me after installing passenger:

1.
```bash
brew install passenger
```

2.
```bash
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
```
