### ISSUE TITLE
Ruby 3 Compatibility

### ISSUE THREAD

**Issue by delonnewman** [rtomayko/shotgun#75]
I'm sure how active the project is at this point, but I ran into an issue with Ruby 3 keyword arguments.  The fork is here: https://github.com/delonnewman/shotgun please advise on how to proceed. 

It's my intention to do some testing on older versions of Ruby (I'll need to do some research and refresh my memory on how to best handle compatibility with older versions).

The issue came about while using Ruby 3.0.1, Puma 5.2.2, and Shotgun 0.9.2.

**Comment by tom-lord** [comment]
> please advise on how to proceed

The standard practice would be to open a PR on this project with your proposed fix. (And also to clean it up a little - there's no need fo that `TODO` comment 😸 )

You click the green ["New Pull Request" button](https://github.com/rtomayko/shotgun/compare), then "compare across forks", and select your repository.

However, there's actually already an open PR for the same fix: https://github.com/rtomayko/shotgun/pull/74

> testing on older versions of Ruby

This change should work fine on ruby version `2.x`, too..

**Comment by delonnewman** [comment]
> The standard practice would be to open a PR on this project with your proposed fix. (And also to clean it up a little - there's no need fo that TODO comment 😸 )

Thank you. The comment was for myself, which is why I hadn't submitted a PR.

> However, there's actually already an open PR for the same fix: #74

So this is all set then?

**Comment by tom-lord** [comment]
> So this is all set then?

All set as in what, exactly? There's nothing more to be done on this project, if that's what you mean. If/when the author sees the PR, they'll likely approve it and release a new gem version.

However, the author of this library has been active on github for quite some time. Perhaps someone else (you??) would rather take ownership with an "official" fork with the ruby 3.0-syntax fixed. Or perhaps you're happy to run your application using the branch for now.

**Comment by delonnewman** [comment]
> There's nothing more to be done on this project, if that's what you mean.

I was speaking with regard to this fix. Thank you for for pointing out that there was already a PR.

> However, the author of this library has been active on github for quite some time. Perhaps someone else (you??) would rather take ownership with an "official" fork with the ruby 3.0-syntax fixed.

Thank you for the help, I was assuming that you were involved in the project.
